# Generated by Django 5.0.3 on 2024-04-06 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'glucose_label',
            },
        ),
        migrations.RemoveField(
            model_name='glucose',
            name='label',
        ),
        migrations.CreateModel(
            name='InsulineLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('insuline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_management.insulin')),
            ],
            options={
                'db_table': 'insuline_label',
            },
        ),
        migrations.CreateModel(
            name='MedicineLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_management.medicine')),
            ],
            options={
                'db_table': 'medicine_label',
            },
        ),
        migrations.CreateModel(
            name='PressureLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker_management.pressure')),
            ],
            options={
                'db_table': 'pressure_label',
            },
        ),
        migrations.AddField(
            model_name='glucose',
            name='label',
            field=models.ManyToManyField(blank=True, to='tracker_management.glucoselabel'),
        ),
    ]
