# Generated by Django 5.0.3 on 2024-04-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_management', '0002_glucoselabel_remove_glucose_label_insulinelabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicmedicine',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='glucoselabel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insulinelabel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medicinelabel',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pressurelabel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
